version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        updates:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      GitHubActions-dependencies:
        patterns:
          - "*"
